[package]
name = "static-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.1.0", features = ["macros"] }
mimalloc = { version = "0.1.39", default-features = false }