name: Run benchmarks

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            async-graphql/target
            juniper/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      #- uses: actions/cache@v3
      #  with:
      #    path: ~/.local/share/virtualenvs
      #    key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          curl -fsSL https://crystal-lang.org/install.sh | sudo bash
          nix-shell --quiet --run "mix local.hex --force"
          nix-shell --quiet --run "mix local.rebar --force"
      - name: Run benchmarks
        run: nix-shell --quiet --run ./run.cr
      - name: Push readme
        run: |
          git config --global user.name "Jakob Gillich"
          git config --global user.email "jakob@gillich.me"
          git add README.md
          git commit -m "update readme"
          git push
